version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: demo-app
    container_name: demo-app
    volumes:
      - uploads_volume:/app/uploads
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-proxy
    container_name: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  uploads_volume: